title-heading: false
theme: jekyll-theme-slate

plugins:
  - jekyll-seo-tag
# Remove header and footer
defaults:
  -
    scope:
      path: "" # empty for all files
    values:
      layout: "default"
      remove_header: true
      remove_footer: true