#
# name: ""
# title: routepoison.com
# title-heading: false
# description: RP LLC
# baseurl: "/routepoison.github.io" # The subpath of your site, e.g. /blog/

# theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
# Remove header and footer
defaults:
  -
    scope:
      path: "" # empty for all files
    values:
      layout: "default"
      remove_header: true
      remove_footer: true